Move ApplicationInstance creation to the service
hypothesis/lms pull request #2827
Opened 2021-06-15 15:38 UTC by marcospri

Looking for where the initial AI.settings were set and found this which I think belongs to the service rather than the view

2021-06-15 15:39 UTC, marcospri commented on lms/services/application_instance.py
> +    def create(  # pylint:disable=too-many-arguments
Not sure if the `from_url` part is need, it just puts the URL value on the URL column

2021-06-15 15:40 UTC, marcospri commented on lms/services/application_instance.py
> +        ai = ApplicationInstance.build_from_lms_url(
This could be on the service or stay on the model. I left it on the model which I think it makes sense.

2021-06-15 15:41 UTC, marcospri commented on lms/services/application_instance.py
> +            settings={"canvas": {"sections_enabled": bool(developer_key)}},
All AI are created thru that view at the moment so I think it's ok to keep this hard coded here.

2021-06-16 15:30 UTC, jon-betts requested changes
I think this removes some code out of the view and pushes it down, but stops short of coalescing all of the behavior into one place. This results in the code for creating an application instance actually being more spread out than before.

This also results in hybrid tests in the service which don't benefit from isolating the layer below and end up quite long as a result, but also don't completely test `build_from_lms_url`.

As far as I can tell `build_from_lms_url` is only called here, so we end up having to test more different paths than our code can actually create, because we have a more general interface to `build_from_lms_url` than it's possible to exercise. I think unifying the two and testing in one place would reduce the number of tests and possible code paths.

I'd suggest:

* Moving the `if not developer_key...` part to the other code (it's basically the other side of an if that's already there) + the settings initialisation
* Either:
    * Move everything about creating into the service
    * Don't have anything there at all (if it's just calling that then putting it in the DB)

This might be a good idea to have a look at the `if` block and private functions in `build_from_lms_url` too (plus the name) as they are needlessly confusing.

2021-06-16 15:30 UTC, jon-betts commented on tests/unit/lms/services/application_instance_service_test.py
>          return factory(mock.sentinel.context, pyramid_request)
I don't think we should be creating the service via the factory in the tests. The factory depends on the service, but the service does not depend on the factory, and it makes seeing the linkage more obscure

2021-06-16 15:30 UTC, jon-betts commented on tests/unit/lms/services/application_instance_service_test.py
> +        )
There's really only 4 or so lines of code in the function at the moment, so it's probably worth thinking about how we can test it without quite as much in the tests.

Some suggestions:

 * Parameterise additions to `new_application_instance_params`
 * Pack some more assertions about outcomes into fewer tests
 * Package the call, flush, retrieve into a caller?

2021-06-22 08:26 UTC, marcospri commented
Found a service circular dependency while merging some service and model methods. Might clean this up to only do the bits about `create` and left the rest for a different PR.

2021-07-07 08:32 UTC, closed without merging