Add some extra log output to try and narrow down failures
hypothesis/lms pull request #3091
Opened 2021-09-08 15:21 UTC by jon-betts

2021-09-08 17:14 UTC, lyzadanger approved these changes
Thanks! This fixes the ol' glitch.

2021-09-09 11:13 UTC, seanh requested changes

2021-09-09 11:13 UTC, seanh commented on bin/update_dev_data.py
> +            raise
I think we can remove the `except`. There's a [unique constraint on `(resource_link_id, tool_consumer_instance_guid)`](https://github.com/hypothesis/lms/blob/d62445c2c020eb54c78060c33a943d07938f8a30/lms/models/assignment.py#L26) so the code is gonna work correctly now. Bug fixed

2021-09-09 13:52 UTC, seanh requested changes

2021-09-09 13:52 UTC, seanh commented on bin/update_dev_data.py
> +from sqlalchemy.exc import MultipleResultsFound
Unused import. PyLint doesn't seem to be doing its job for some reason

2021-09-09 14:06 UTC, seanh approved these changes

2021-09-10 11:52 UTC, merged