Bulk upsert helper
hypothesis/lms pull request #3518
Opened 2021-12-17 09:37 UTC by marcospri

2021-12-17 09:46 UTC, marcospri commented on lms/services/_upsert.py
> +    ).returning(*index_elements_columns)
If the index_elements_columns where enough to identify the rows for the upsert it will work to get the rows back.

2021-12-17 09:46 UTC, marcospri commented on lms/services/_upsert.py
> +        db.query(model_class).filter(tuple_(*index_elements_columns).in_(result)).all()
This makes an extra query but it mean that we can return full ORM objects

2021-12-17 09:46 UTC, marcospri commented on lms/services/grouping.py
> +    class _GroupingData(TypedDict):
This might be a bit meh I still prefer it over just a list of random dicts, it's the same in practice but IMO this more explicit than a long comment.

2021-12-17 09:46 UTC, marcospri commented on lms/services/grouping.py
> +            del grouping_data["tool_consumer_instance_guid"]
This is not great, instead of modifying the original dict I think it would be better to crate a new dict with just the required keys.

2021-12-17 09:46 UTC, marcospri commented on tests/unit/conftest.py
> +    return ai
We need to flush the AI to get the PK populated.

2021-12-17 09:46 UTC, marcospri commented on tests/unit/lms/db/_bulk_action_test.py
> +        upsert_rows = [
I didn't move these tests, just tweaked them to make sure that the changes didn't break it.

2021-12-17 09:54 UTC, marcospri commented on lms/services/_upsert.py
> +    return (
This function already takes a few parameters but maybe this part could also be under a boolean flag `return_orm_objects` or similar.

If you just want to upsert and forget like we do with files you don't want to pay the price for this query + serializing all the objects.

2022-01-19 12:49 UTC, seanh requested changes
Is `db/_bulk_action.py` really needed anymore? It looks like `services/_upsert.py::bulk_upsert()` is pretty much a standalone function, or could be, and then `GroupingService` seems to just call `services/_upsert.py::bulk_upsert()` directly?

I wonder if we want to do a refactor first to change `db/_bulk_action.py` into just a services helper function and change its existing users to use it that way?

I think that may result in more straightforward and easier to understand code: just a function with parameters and a docstring is quite easy to follow. The existing bulk upsert stuff is quite unique and unusual: you have this `BulkAction` class that's attached to SQLAlchemy via a custom session, and also bulk action configs on the models, etc.

2022-01-19 12:49 UTC, seanh commented on lms/services/_upsert.py
> +    return [(c.name, c.onupdate.arg) for c in model_details.c if c.onupdate]
I wonder if we can avoid the cleverness here? I think the only column that has `onupdate` in the LMS app is the `updated` column on various models and its value is always `sa.func.now()`. I wonder if we could just have hard-coded code for that particular column

2022-01-24 09:42 UTC, marcospri commented
Cleaner version on https://github.com/hypothesis/lms/pull/3518

2022-01-24 09:42 UTC, closed without merging