Update `ContentSelector` to use non-deprecated components from pattern library
hypothesis/lms pull request #5028
Opened 2023-02-13 17:24 UTC by acelaya

Refactor `ContentSelector` to replace deprecated components from the pattern library by their "next" equivalents.

This PR is part of #5013

2023-02-13 17:24 UTC, acelaya commented on lms/static/scripts/frontend_apps/components/ContentSelector.tsx
> -            type="button"
This is now the default value.

2023-02-13 17:39 UTC, acelaya commented on yarn.lock
> +  version "5.9.1"
Upgrading to latest version of the pattern library, which makes sure the default value for `type` attribute in buttons is `button`.

2023-02-14 08:03 UTC, acelaya commented
> `frontend-shared` is at `5.9.1` on `main` now, so you'll want to remove the commit that bumps it from this branch

Done!

2023-02-14 13:16 UTC, lyzadanger commented
We've got a bit of a problem here, one we knew was coming.

Before these changes in Canvas, with a bunch of features enabled:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/439947/218748202-1dd79a7b-2ad1-455b-a230-2750abca37ef.png">

After:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/439947/218748432-1e44cbb4-dfb1-4ebd-9c8a-78714c2c3365.png">

I see an immediate workaround, but I'll need to follow up on this overall situation ASAP.

Suggested workaround: edit `_FilePickerApp.scss` (one of the very last remaining bits of non-Tailwind CSS in our apps), change `.FilePickerApp__form` to set `margin-top` to `1rem` instead of `10vh`. This results in this layout:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/439947/218749481-1025e386-81fa-4f81-aa45-3741e2b65192.png">

I think that is acceptable for the moment, but please test through the whole assignment-configuration workflow in both Canvas and another LMS (BlackBoard is an option) and in a couple of browsers.

I'll bring this situation up in the sync today and ask if I can remediate it more better.

2023-02-14 13:17 UTC, lyzadanger requested changes
This particular interface is rickety and right on the edge of manageable and needs a redesign (this has been a known issue, but now it's becoming urgent, see my longer comment).

We'll need to reduce the top margin of the overall layout before merging this.

2023-02-14 14:14 UTC, acelaya commented
@lyzadanger I have pushed the styles change.

I have also tested it in D2L and Blackboard, and those have more space for the component, so there should be no problem.

2023-02-14 14:32 UTC, lyzadanger approved these changes
OK, let's get this landed. I will be following up soon with changes to `FilePickerApp` and this layout.

2023-02-14 14:37 UTC, merged