Add folders and pages scopes to Canvas scopes error
hypothesis/lms pull request #5769
Opened 2023-10-18 11:55 UTC by robertknight

The error message shown to users when authorization fails due to missing scopes, was missing scopes for folders and pages.

See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1697628340572009

2023-10-18 12:10 UTC, seanh requested changes

2023-10-18 12:10 UTC, seanh commented on lms/views/api/canvas/authorize.py
> +
Maybe we could avoid the potential for this `ALL_SCOPES` list to get out of date when another `FOO_SCOPE` constant is added by changing them all to a dict:

```python
SCOPES = {
    "files": (
        "url:GET|/api/v1/courses/:course_id/files",
        "url:GET|/api/v1/files/:id/public_url",
    ),
    "folders": (...),
    ...
}

ALL_SCOPES = set(scope for scopes in SCOPES.values() for scope in scopes)
```

Incidentally this also removes the possibility of duplicate scopes being listed.

2023-10-19 11:36 UTC, robertknight commented
I have made the changes you requested @seanh. @marcospri asked in https://hypothes-is.slack.com/archives/C4K6M7P5E/p1697631738690499?thread_ts=1697628340.572009&cid=C4K6M7P5E to delay merging this until we are closer to releasing the feature to early adopters, so I will defer actually merging this once approved.

2023-10-24 13:42 UTC, seanh approved these changes

2023-10-26 08:41 UTC, robertknight commented
We decided in https://hypothes-is.slack.com/archives/C4K6M7P5E/p1698309357515999 to go ahead and merge this, even though the Canvas Pages integration is still turned off for most institutions. If the new scopes are queried, we'll explain that they are for an upcoming feature and are not technically required until the feature is turned on.

2023-10-26 09:25 UTC, merged