Add role='alert' to UIMessage
hypothesis/lms pull request #6035
Opened 2024-02-05 16:24 UTC by acelaya

Closes #6012 

From the [2024 VPAT review](https://docs.google.com/document/d/1YdYr5jIsKEm4CkOQF9un3LUc-A8xLtwFP5kWbNpqYOM/edit#heading=h.gjdgxs), we were suggested these changes to ensure `FilePicker` errors are properly announced by screen readers:

> Recommendation for error messages
> To improve the accessibility of the input: 
> * Add a role=”alert” to the error message to announce it to assistive technology users in real time. 
> * Add an aria-describedby attribute to the input with a value that points to the id of the error message. This will communicate the error to users when they are within the input field.

This PR implements only the first one, because adding both causes the error to be announced twice if the input is focused at the moment it's rendered.

This is probably what happens in the majority of cases, if an invalid value is introduced and then <kbd>Enter</kbd> is pressed.

By adding `role="alert"` to the error, screen readers announce it once as soon as it happens, regardless of how it was triggered (pressing <kbd>Enter</kbd> or clicking "Submit").

It has one drawback though. Using the `aria-describedby` approach, the error is announced every time the input is focused, while using `role="alert"` in the error, results in the message being announced only once.

### TODO

- [ ] Try other screen readers

2024-02-06 10:49 UTC, acelaya commented
Note: At one point when implementing this, I noticed the screen reader was announcing the error message twice, and decided to implement only one of the suggestions.

Then, while testing other approaches the following day, I could not reproduce this anymore, but would be good to have someone else testing this as well.

2024-02-07 11:35 UTC, robertknight requested changes
I see a couple of issues with the implementation here. More generally I think we ought to move this functionality to the pattern library, since it really is an essential feature for input fields in many applications that we will be building.

- There isn't a screen-reader accessible equivalent of the red border ring indicating the invalid state of the field. The docs I linked from w3.org explain how to do this with `aria-invalid`
- The VPAT review and other documentation I was able to find (see comments) recommended `aria-describedby` for the error message rather than `aria-labelledby`. The `aria-labelledby` also ends up conflicting with the control's `aria-label`.

2024-02-07 11:42 UTC, acelaya commented
> The VPAT review and other documentation I was able to find (see comments) recommended aria-describedby for the error message rather than aria-labelledby. The aria-labelledby also ends up conflicting with the control's aria-label.

Ugh, this is actually an overlook, and I think it explains why in my first attempt I experienced duplicated messages being announced (because I used `aria-describedby`), while I then could not reproduce it anymore (because I unconsciously switched to `aria-labelledby`).

2024-02-07 11:43 UTC, acelaya commented on lms/static/scripts/frontend_apps/components/ErrorMessage.tsx
> + * always-present [aria-live="polite"] container
Yeah, this is a mistake. See https://github.com/hypothesis/lms/pull/6035#issuecomment-1931867735

2024-02-07 11:43 UTC, acelaya commented on lms/static/scripts/frontend_apps/components/JSTORPicker.tsx
> +              aria-labelledby={errorId}
Yeah, this is a mistake. See https://github.com/hypothesis/lms/pull/6035#issuecomment-1931867735

2024-02-08 15:43 UTC, acelaya commented
Based on Rob's feedback, we discussed a different approach for this, so I'll close this PR for now.

2024-02-08 15:43 UTC, closed without merging